src/Entity/Customer.php
<?php

declare(strict_types=1);

namespace App\Entity;

use Cocur\Slugify\Slugify;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use HakimCh\SeoBundle\Contracts\SeoEntityInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="type", type="string")
 * @ORM\DiscriminatorMap({"general" = "Customer", "driver" = "CustomerDriver", "official" = "CustomerOfficial", "professional" = "CustomerProfessional"})
 * @ORM\Table(
 *     uniqueConstraints={
 *         @ORM\UniqueConstraint(name="customer_unique", columns={"email", "type"})
 *     }
 * )
 * @ORM\HasLifecycleCallbacks
 */
class Customer implements EntityInterface, SeoEntityInterface
{
    public const STATUS_PENDING = 'pending';
    public const STATUS_CONFIRMED = 'confirmed';

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     *
     * @param int|null
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=125, nullable=true)
     * @Assert\NotBlank
     * @Assert\Length(min="2")
     */
    protected $firstName;

    /**
     * @ORM\Column(type="string", length=125, nullable=true)
     */
    protected $lastName;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank
     * @Assert\Length(min="70")
     */
    protected $content;

    /**
     * @ORM\Column(type="json")
     */
    protected $pictures;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     * @Assert\Email
     */
    protected $email;

    /**
     * @ORM\Column(type="json", nullable=true)
     */
    protected $phones;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $website;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $facebook;

    /**
     * @ORM\Column(type="string", length=15, nullable=true)
     */
    protected $status = self::STATUS_PENDING;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $count = 0;

    /**
     * @var string
     */
    protected $type;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $birthAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $createdAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $updatedAt;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Category", inversedBy="customers")
     * @ORM\JoinTable(name="customer_category")
     *
     * @var Category[]
     */
    protected $categories;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\CustomerSubscription", mappedBy="customer", cascade={"persist"})
     */
    protected $subscriptions;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\CustomerStory", mappedBy="customer", cascade={"persist", "remove"})
     */
    protected $stories;

    public function __construct()
    {
        $this->categories = new ArrayCollection();
        $this->subscriptions = new ArrayCollection();
        $this->stories = new ArrayCollection();
        $this->createdAt = new DateTime();
    }

    /**
     * @ORM\PreUpdate
     * @ORM\PrePersist
     */
    public function onUpdate(): void
    {
        $this->updatedAt = new DateTime();
    }

    /**
     * @ORM\PrePersist
     */
    public function onInsert(): void
    {
        $this->count = $this->count ?? 0;
        $this->status = $this->status ?? self::STATUS_PENDING;
        $this->createdAt = $this->createdAt ?? new DateTime();
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(?string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(?string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getTitle(): string
    {
        return trim($this->firstName.' '.$this->lastName);
    }

    public function getUsername(): ?string
    {
        return Slugify::create()->slugify($this->getTitle());
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getPictures(): array
    {
        return $this->pictures ?? [];
    }

    public function getProfilePicture(): ?string
    {
        return $this->pictures['profile'] ?? null;
    }

    public function getSlideShowPictures(): array
    {
        $pictures = $this->pictures ?? [];
        if (\array_key_exists('profile', $pictures)) {
            unset($pictures['profile']);
        }

        return $pictures;
    }

    public function setPictures(array $pictures): self
    {
        $this->pictures = $pictures;

        return $this;
    }

    public function addPictures(array $photos): self
    {
        $this->pictures = array_replace($this->pictures, $photos);

        return $this;
    }

    public function addPicture(string $key, string $value): self
    {
        $this->pictures[$key] = $value;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function getRecipient(): array
    {
        return [$this->email => $this->getTitle()];
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPhones(): ?array
    {
        return $this->phones;
    }

    public function setPhones(?array $phones): self
    {
        $this->phones = $phones;

        return $this;
    }

    public function getWebsite(): ?string
    {
        return $this->website;
    }

    public function setWebsite(?string $website): self
    {
        $this->website = $website;

        return $this;
    }

    public function getFacebook(): ?string
    {
        return $this->facebook;
    }

    public function setFacebook(?string $facebook): self
    {
        $this->facebook = $facebook;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getCount(): ?int
    {
        return $this->count;
    }

    public function addPageView(int $count = 1): self
    {
        $this->count += $count;

        return $this;
    }

    public function setCreatedAt(DateTime $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getCreatedAt(): ?DateTime
    {
        return $this->createdAt;
    }

    public function getUpdatedAt(): ?DateTime
    {
        return $this->updatedAt;
    }

    public function getBirthAt(): ?DateTime
    {
        return $this->birthAt;
    }

    public function setBirthAt(?DateTime $birthAt): self
    {
        $this->birthAt = $birthAt;

        return $this;
    }

    /**
     * @return Category[]|Collection
     */
    public function getCategories()
    {
        return $this->categories;
    }

    /**
     * @param Category[] $categories
     *
     * @return Customer
     */
    public function setCategories(array $categories): self
    {
        $this->categories = $categories;

        return $this;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        if ($this->categories->contains($category)) {
            $this->categories->removeElement($category);
        }

        return $this;
    }

    public function clearCategories(): self
    {
        $this->categories->clear();

        return $this;
    }

    /**
     * @return Collection|CustomerSubscription[]
     */
    public function getSubscriptions()
    {
        return $this->subscriptions;
    }

    public function addSubscription(CustomerSubscription $subscription): self
    {
        if (!$this->subscriptions->contains($subscription)) {
            $this->subscriptions[] = $subscription;
            $subscription->setCustomer($this);
        }

        return $this;
    }

    /**
     * @return Collection|CustomerStory[]
     */
    public function getStories()
    {
        return $this->stories;
    }

    public function addStory(CustomerStory $story): self
    {
        if (!$this->stories->contains($story)) {
            $this->stories[] = $story;
            $story->setCustomer($this);
        }

        return $this;
    }

    public function removeStoryByIndex(int $index): self
    {
        $this->stories->remove($index);

        return $this;
    }
}

src/Entity/Post.php
<?php

declare(strict_types=1);

namespace App\Entity;

use Cocur\Slugify\Slugify;
use DateTime;
use Doctrine\ORM\Mapping as ORM;
use HakimCh\SeoBundle\Contracts\SeoEntityInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="type", type="string")
 * @ORM\DiscriminatorMap({"event" = "PostEvent", "article" = "PostArticle", "deal" = "PostDeal", "classified" = "PostClassified"})
 * @ORM\HasLifecycleCallbacks
 */
abstract class Post implements EntityInterface, SeoEntityInterface
{
    public const STATUS_PUBLISH = 'PUBLISH';
    public const STATUS_DRAFT = 'DRAFT';
    public const STATUS_ARCHIVE = 'ARCHIVED';
    public const STATUS_PENDING = 'PENDING';

    /**
     * @var Category
     */
    protected $category;

    /**
     * @var User
     */
    protected $user;
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     * @Assert\Length(min="5")
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank
     * @Assert\Length(min="70")
     */
    private $content;

    /**
     * @ORM\Column(type="integer")
     */
    private $count;

    /**
     * @ORM\Column(type="json")
     */
    private $pictures = [];

    /**
     * @ORM\Column(type="integer", nullable=true, options={"default" = 1})
     */
    private $isOpenToDiscussion;

    /**
     * @ORM\Column(type="string", length=15)
     */
    private $status;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @return string
     */
    abstract public function getType(): string;

    /**
     * @ORM\PreUpdate
     */
    public function onPreUpdate(): void
    {
        $this->updatedAt = new DateTime();
        $this->slug = Slugify::create()->slugify($this->title);
    }

    /**
     * @ORM\PrePersist
     */
    public function onPrePersist(): void
    {
        $this->count = $this->count ?? 0;
        $this->createdAt = $this->createdAt ?? new DateTime();
        $this->slug = Slugify::create()->slugify($this->title);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): string
    {
        return $this->slug;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCount(): int
    {
        return $this->count;
    }

    public function setCount(int $count): self
    {
        $this->count = $count;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getPictures(): array
    {
        return $this->pictures ?? [];
    }

    /**
     * @param string $key
     *
     * @return string|null
     */
    public function getPicture(string $key)
    {
        return $this->pictures[$key] ?? null;
    }

    /**
     * @return string|null
     */
    public function getMainPicture()
    {
        return !empty($this->pictures) ? current($this->pictures) : null;
    }

    public function setPictures(array $pictures): self
    {
        $this->pictures = $pictures;

        return $this;
    }

    public function addPictures(array $pictures): self
    {
        $this->pictures = array_replace(
            $this->pictures,
            $pictures
        );

        return $this;
    }

    public function addPicture(string $key, string $value): self
    {
        if (!empty($value)) {
            $this->pictures[$key] = $value;
        }

        return $this;
    }

    public function getIsOpenToDiscussion(): bool
    {
        return $this->isOpenToDiscussion ?? false;
    }

    public function setIsOpenToDiscussion(?bool $isOpenToDiscussion): self
    {
        $this->isOpenToDiscussion = $isOpenToDiscussion;

        return $this;
    }

    public function getCreatedAt(): ?DateTime
    {
        return $this->createdAt;
    }

    public function setCreatedAt(DateTime $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?DateTime
    {
        return $this->updatedAt;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getUser(): User
    {
        return $this->user;
    }

    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

templates/blocs/article-md.html.twig
{% if item is defined %}
    <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
        <a class="bloc_related" href="{{ path('blog_detail', {category: item.category.slug, slug: item.slug, id: item.id}) }}">
            <div class="bloc__image" style="background-image:url({{ resize(item.mainPicture, 250, 200, item.type) }})"></div>
            <time datetime="{{ item.createdAt|date('U') }}" class="bloc__date">{{ item.createdAt|date('d/m/Y H:s') }}</time>
            <h3 class="bloc__title">{{ item.title }}</h3>
        </a>
    </div>
{% endif %}

templates/blocs/article.html.twig
{% if item is defined %}
    <article class="item item-cover">
        <a href="{{ path('blog_detail', {category: item.category.slug, slug: item.slug, id: item.id}) }}" class="item-link"></a>
        <div style="background-image: url({{ resize(item.mainPicture, 600, 600, item.type) }})" class="item-image item-image-rounded-border"></div>
        <header class="item-header">
            <h5 class="item-section">{{ item.category.title }}</h5>
            <h2 class="item-title">{{ item.title }}</h2>
            <ul class="item-byline">
                <li>Posté par <a href="{{ path('blog_author', {id: item.user.id, slug: item.user.username }) }}">{{ item.user.title }}</a></li>
                <li><span class="icone meta ion-clock" title="{{ item.createdAt|date('U') }}">{{ item.createdAt|date('d/m/Y') }}</span></li>
            </ul>
        </header>
    </article>
{% endif %}

templates/blocs/classified-md.html.twig
{% if item is defined %}
    <a class="bloc_related" href="{{ path('classified_detail', {city: item.city.slug , category: item.category.slug, type: item.type, slug: item.slug, id: item.id}) }}">
        <div class="bloc__image" style="background-image:url({{ resize(item.mainPicture, 250, 200, item.type) }})"></div>
        <h3 class="bloc__title">{{ item.title }}</h3>
        <time datetime="{{ item.createdAt|date('U') }}" class="bloc__date">{{ item.createdAt|date('d/m/Y à H:i') }}</time>
    </a>
{% endif %}

templates/blocs/classified-sm.html.twig
{% if item is defined %}
    <a class="bloc_article" href="{{ path('classified_detail', {city: item.city.slug , category: item.category.slug, type: item.type, slug: item.slug, id: item.id}) }}">
        <div class="bloc__image" style="background-image: url({{ thumbnail(item.getMainPicture, 80, 80, item.type) }})"></div>
        <h3 class="bloc__title">{{ item.title }}</h3>
        <time datetime="{{ item.createdAt|date('U') }}" class="bloc__date">{{ item.createdAt|date('d/m/Y à H:i') }}</time>
    </a>
{% endif %}

templates/blocs/classified.html.twig
{% if item is defined %}
    <article class="item item-cover">
        <a href="{{ path('classified_detail', {city: item.city.slug, category: item.category.slug, slug: item.slug, id: item.id}) }}" class="item-link"></a>
        <div style="background-image: url({{ resize(item.getPicture('picture1'), 600, 600, 'annonces') }})" class="item-image"></div>
        <div class="item-sticky">
            <div class="item-price">{{ item.price }} Dh</div>
        </div>
        <header class="item-header">
            <h5 class="item-section">
                <a href="{{ path('classified_by_category', {category: item.category.slug}) }}">{{ item.category.title }}</a>
            </h5>
            <h2 class="item-title">{{ item.title }}</h2>
            <ul class="item-byline">
                <li>Localisation <a href="{{ path('classified_by_city', {city: item.city.slug}) }}">{{ item.city.title }}</a></li>
            </ul>
        </header>
    </article>
{% endif %}

templates/blocs/deal-sm.html.twig
{% if item is defined %}
    <a class="bloc_article" href="{{ path('deals_detail', {category: item.category.slug, slug: item.slug, city: item.city.slug, id: item.id}) }}">
        <div class="bloc__image" style="background-image:url({{ resize(item.mainPicture, 80, 80, item.type) }})"></div>
        <h3 class="bloc__title">{{ item.title }}</h3>
        <time datetime="{{ item.createdAt|date('U') }}" class="bloc__date">{{ item.createdAt|date('d/m/Y H:i') }}</time>
        <div class="clearfix"></div>
    </a>
{% endif %}

templates/blocs/deal.html.twig
{% if item is defined %}
    <article class="item item-cover">
        <a href="{{ asset('deals/' ~ item.city.slug ~ '/' ~ item.category.slug ~ '/' ~ item.slug ~ '/' ~ item.id) }}" class="item-link"></a>
        <div style="background-image: url({{ resize(item.getPicture('picture1'), 600, 600, 'deals') }})" class="item-image"></div>
        <div class="item-sticky">
            <div class="item-price">{{ item.price }} Dh</div>
            <div class="item-discount">{{ item.discount }}%</div>
        </div>
        <header class="item-header">
            <h5 class="item-section">
                <a href="{{ path('deals_category', {category: item.category.slug}) }}">{{ item.category.title }}</a>
            </h5>
            <h2 class="item-title">{{ item.title }}</h2>
            <ul class="item-byline">
                <li>Localisation <a href="{{ path('deals_city', {city: item.city.slug}) }}">{{ item.city.title }}</a></li>
                {% if item.endAt %}
                    <li class="item-event">Se termine le <span title="{{ item.endAt|date('U') }}">{{ item.endAt|date('d/m/Y') }}</span></li>
                {% endif %}
            </ul>
        </header>
    </article>
{% endif %}

templates/blocs/driver.html.twig
{% if item is defined %}
    <article class="item item-cover">
        <a href="{{ path('directory_driver_show', {username: item.username, id: item.id}) }}" class="item-link"></a>
        <div style="background-image: url({{ resize(item.profilePicture, 400, 400, item.type) }})" class="item-image item-image-rounded-border"></div>
        <div class="item-job">{{ item.type }}</div>
        <header class="item-header">
            <h2 class="item-title">{{ item.title }}</h2>
            <ul class="item-byline">
                <li>{{ item.club|raw|upper }}</li>
                <li>{{ item.vehicle|raw|upper }}</li>
            </ul>
        </header>
    </article>
{% endif %}

templates/blocs/empty-bloc.html.twig
<div class="empty-bloc">
    Cette section semble triste, veuillez ajouter quelques entrées.
</div>

templates/blocs/event.html.twig
{% if item is defined %}
    <article class="item item-cover{% if index is defined and index == 0 %} next-event{% endif %}">
        <a href="{{ path('events_detail', { category: item.category.slug|default('general'), slug: item.slug, id: item.id }) }}" class="item-link"></a>
        <div style="background-image: url({{ thumbnail(item.mainPicture, 600, 600, item.type) }})" class="item-image item-image-rounded-border"></div>
        <header class="item-header">
            <h3 class="item-section">
                <a href="{{ path('events_category', { category: item.category.slug|default('general') }) }}">{{ item.category.title|default('Général') }}</a>
            </h3>
            <h2 class="item-title">
                <a href="{{ path('events_detail', { category: item.category.slug|default('general'), slug: item.slug, id: item.id }) }}">
                    {{ item.title }}
                </a>
            </h2>
            <ul class="item-byline">
                <li>Du {{ item.startAt|date('d/m/Y') }}</li>
                <li>au {{ item.endAt|date('d/m/Y') }}</li>
            </ul>
        </header>
    </article>
{% endif %}

templates/blocs/flashBag.html.twig
{% set flashBag = app.session.flashBag.all() %}
{% if flashBag | length > 0 %}
    {% for type, messages in flashBag %}
        <ul class="alert alert-{{ type }}">
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endfor %}
{% endif %}

templates/blocs/og-metas.html.twig
{% if url is defined %}
    <meta property="og:url" content="{{ url }}" />
    <link rel="canonical" href="{{ url }}" />
{% endif %}
{% if image is defined %}
    <meta property="og:image" content="{{ image }}" />
    <meta name="twitter:image" content="{{ image }}" />
    <meta name="twitter:image:src" content="{{ image }}" />
{% endif %}

templates/blocs/professional.html.twig
{% if item is defined %}
    <article class="item item-shadow">
        <div class="item-image item-image-rounded-border">
            <img src="{{ thumbnail(item.profilePicture, 380, 200, item.type, true) }}" alt="Photo de profile">
        </div>
        <div class="item-job">{{ item.type|trans }}</div>
        <header class="item-header">
            <h2 class="item-title">
                <a href="{{ path('directory_professional_show', {username: item.username, id: item.id}) }}" class="item-link">{{ item.title }}</a>
            </h2>
        </header>
        <div class="item-action">
            <a href="{{ path('directory_professional_show', {username: item.username, id: item.id}) }}" class="btn-complete btn-rounded">En savoir plus</a>
        </div>
    </article>
{% endif %}

templates/blocs/slide-show.html.twig
{% if photos is defined %}
    {% set count = photos|length %}
    {% set galery = count >= min|default(1) %}
    {% if count > 0 %}
        {% if count > 1 %}
            <div class="slider">
                <div class="slider-items">
                    {% set i = 0 %}
                    {% for photo in photos %}
                        {% set src = thumbnail(photo, 670, 400, targetDir, true) %}
                        <div class="slider-item">
                            <a class="slider-controller controller-preview" href="{{ src }}" data-lightbox="Galerie {{ title }}" data-title="Photo de {{ title }}">
                                <i class="ion ion-md-search"></i>
                            </a>
                            <img src="{{ src }}" alt="Photo de {{ title }} n°{{ i }}">
                        </div>
                        {% set i = i + 1 %}
                    {% endfor %}
                </div>
                <button class="slider-controller controller-prev">
                    <i class="ion ion-ios-arrow-back"></i>
                </button>
                <button class="slider-controller controller-next">
                    <i class="ion ion-ios-arrow-forward"></i>
                </button>
            </div>
        {% elseif galery %}
            {% set src = asset('/build/images/' ~ targetDir ~ '/' ~ photos|first) %}
            <div class="article__image">
                <img src="{{ src }}" class="img-responsive" alt="Photo de {{ title }} N°1">
            </div>
        {% endif %}
    {% endif %}
{% endif %}