src/Entity/PostDeal.php
<?php

declare(strict_types=1);

namespace App\Entity;

use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PostDealRepository")
 */
class PostDeal extends Post
{
    public const TYPE_LABEL = 'deal';
    public const MAX_POST_PER_PAGE = 24;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="deals")
     * @ORM\JoinColumn(nullable=true)
     */
    protected $category;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="deals")
     * @ORM\JoinColumn(nullable=false)
     */
    protected $user;
    /**
     * @ORM\Column(type="decimal", precision=10, scale=0)
     * @Assert\NotBlank
     * @Assert\GreaterThan(0)
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank
     * @Assert\GreaterThan(0)
     */
    private $discount;

    /**
     * @ORM\Column(type="text")
     */
    private $address;

    /**
     * @ORM\Column(type="json")
     */
    private $requirement = ['min' => 0, 'max' => 0];

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $startAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $endAt;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\City", inversedBy="deals")
     */
    private $city;

    /**
     * @ORM\OneToMany(targetEntity="PostDealOrders", mappedBy="deal")
     */
    private $dealOrders;

    public function __construct()
    {
        $this->dealOrders = new ArrayCollection();
    }

    public function getDiscountedPrice(): ?float
    {
        if (!$this->price) {
            return null;
        }

        return $this->price * (1 - ($this->getDiscount() / 100));
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getDiscount(): ?int
    {
        return $this->discount;
    }

    public function setDiscount(int $discount): self
    {
        $this->discount = $discount;

        return $this;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setRequirement(int $min, int $max = 0): self
    {
        $this->requirement = compact('min', 'max');

        return $this;
    }

    public function getRequirement(): ?array
    {
        return $this->requirement;
    }

    public function getMinimumRequirement(): int
    {
        return $this->requirement['min'] ?? 0;
    }

    public function getMaximumRequirement(): int
    {
        return $this->requirement['max'] ?? 0;
    }

    public function setMinimumRequirement(int $minimum): self
    {
        $this->requirement['min'] = $minimum;

        return $this;
    }

    public function setMaximumRequirement(int $maximum): self
    {
        $this->requirement['max'] = $maximum;

        return $this;
    }

    public function hasMinimumRequirement(): bool
    {
        return $this->getMinimumRequirement() > 0;
    }

    public function hasMaximumRequirement(): bool
    {
        return $this->getMaximumRequirement() > 0;
    }

    public function getStartAt(): ?DateTime
    {
        return $this->startAt;
    }

    public function setStartAt(?DateTime $startAt): self
    {
        $this->startAt = $startAt;

        return $this;
    }

    public function getEndAt(): ?DateTime
    {
        return $this->endAt;
    }

    public function setEndAt(?DateTime $endAt): self
    {
        $this->endAt = $endAt;

        return $this;
    }

    public function isOpen(): bool
    {
        return null === $this->endAt;
    }

    public function getCity(): ?City
    {
        return $this->city;
    }

    public function setCity(City $city): self
    {
        $this->city = $city;

        return $this;
    }

    /**
     * @return Collection|PostDealOrders[]
     */
    public function getDealOrders()
    {
        return $this->dealOrders;
    }

    public function addDealOrder(PostDealOrders $order): self
    {
        if (!$this->dealOrders->contains($order)) {
            $this->dealOrders[] = $order;
            $order->setDeal($this);
        }

        return $this;
    }

    /**
     * @return string
     */
    public function getType(): string
    {
        return self::TYPE_LABEL;
    }
}

src/Controller/InfinityGauntlet/UsersController.php
<?php

declare(strict_types=1);

namespace App\Controller\InfinityGauntlet;

use App\Entity\User;
use App\Form\DeleteType;
use App\Form\UserProfileType;
use App\Form\UserType;
use App\Repository\UserRepository;
use App\Security\Encoder\LegacyEncoder;
use Doctrine\ORM\EntityManagerInterface;
use HakimCh\PaginateBundle\Services\Paginate;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/user", name="backend_users_")
 */
class UsersController extends AbstractController
{
    /**
     * @Route("/{pageName}/{page}", defaults={"pageName" = "page", "page" = 1}, requirements={"pageName" = "page", "page" = "[\d]+"}, name="show")
     *
     * @param UserRepository $repository
     * @param Paginate       $paginate
     *
     * @return Response
     */
    public function show(UserRepository $repository, Paginate $paginate): Response
    {
        $query = $repository->getQueryBuilder();

        return $this->render('admin/users/show.html.twig', [
            'paginate' => $paginate->setItemsPerPage(16)->make($query),
        ]);
    }

    /**
     * @Route("/add", name="add")
     *
     * @param Request                $request
     * @param EntityManagerInterface $em
     *
     * @return Response
     */
    public function add(Request $request, EntityManagerInterface $em): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($user);
            $em->flush();
            $this->addFlash('success', "L'element a été ajouté avec succès");

            return $this->redirectToRoute('backend_users_update', ['id' => $user->getId()]);
        }

        return $this->render('admin/users/save.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/update/{id}", name="update")
     *
     * @param User                   $user
     * @param Request                $request
     * @param EntityManagerInterface $em
     *
     * @return Response
     */
    public function update(User $user, Request $request, EntityManagerInterface $em): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($user);
            $em->flush();
            $this->addFlash('success', "L'element a été mis à jour avec succès");

            return $this->redirectToRoute('backend_users_update', ['id' => $user->getId()]);
        }

        return $this->render('admin/users/save.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/profile", name="profile")
     *
     * @param Request                $request
     * @param EntityManagerInterface $em
     * @param LegacyEncoder          $encoder
     *
     * @return Response
     */
    public function profile(Request $request, EntityManagerInterface $em, LegacyEncoder $encoder)
    {
        /** @var User $user */
        $user = $this->getUser();
        $currentPassword = $user->getPassword();
        $form = $this->createForm(UserProfileType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if (null === ($newPassword = $user->getPassword())) {
                $user->setPassword($currentPassword);
            } else {
                $user->setEncodedPassword($encoder);
            }
            $em->persist($user);
            $em->flush();
        }

        return $this->render('admin/single/profile.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/remove/{id}", name="remove")
     *
     * @param User                   $user
     * @param Request                $request
     * @param EntityManagerInterface $em
     *
     * @return Response
     */
    public function remove(User $user, Request $request, EntityManagerInterface $em): Response
    {
        $form = $this->createForm(DeleteType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->remove($user);
            $em->flush();
            $this->addFlash('danger', "L'element a été supprimer avec succès");

            return $this->redirectToRoute('backend_users_show');
        }

        return $this->render('admin/single/remove.html.twig', [
            'form' => $form->createView(),
            'element' => 'Utilisateur: '.$user->getTitle(),
        ]);
    }
}

src/Controller/Post/DealsController.php
<?php

declare(strict_types=1);

namespace App\Controller\Post;

use App\Entity\PostDeal;
use App\Entity\User;
use App\Normalizers\DealNormalizer;
use App\Repository\CategoryRepository;
use Exception;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/deals", name="deals_")
 */
class DealsController extends AbstractPostController
{
    /**
     * @var string
     */
    protected $entityClassName = PostDeal::class;
    /**
     * @var string
     */
    protected $normalizer = DealNormalizer::class;
    /**
     * @var string
     */
    protected $postType = 'deal';
    /**
     * @var int
     */
    protected $itemsPerPage = PostDeal::MAX_POST_PER_PAGE;

    /**
     * @Route("/{pageName}/{page}", defaults={"pageName" = "page", "page" = 1}, requirements={"pageName" = "page", "page" = "[\d]+"}, name="home")
     *
     * @throws Exception
     *
     * @return Response
     */
    public function list(): Response
    {
        return $this->render(
            'deals/index.html.twig',
            $this->generateListParameters()->toArray()
        );
    }

    /**
     * @Route("/categorie/{category}/{pageName}/{page}", defaults={"pageName" = "page", "page" = 1}, name="category", requirements={"category" = "[\w-]+", "pageName" = "page", "page" = "[\d]+"})
     *
     * @param string $category
     *
     * @throws Exception
     *
     * @return Response
     */
    public function listByCategory(string $category): Response
    {
        return $this->render(
            'deals/index.html.twig',
            $this->generateListParameters(['category' => $category])->toArray()
        );
    }

    /**
     * @Route("/ville/{city}/{pageName}/{page}", defaults={"pageName" = "page", "page" = 1}, name="city", requirements={"category" = "[\w-]+", "pageName" = "page", "page" = "[\d]+"})
     *
     * @param string $city
     *
     * @throws Exception
     *
     * @return Response
     */
    public function listByCity(string $city): Response
    {
        return $this->render(
            'deals/index.html.twig',
            $this->generateListParameters(['city' => $city])->toArray()
        );
    }

    /**
     * @Route("/auteur/{id}/{slug}/{pageName}/{page}", defaults={"pageName" = "page", "page" = 1}, name="author", requirements={"id" = "[\d]+", "pageName" = "page", "page" = "[\d]+"})
     *
     * @param User $user
     *
     * @throws Exception
     *
     * @return Response
     */
    public function listByUser(User $user): Response
    {
        return $this->render(
            'deals/index.html.twig',
            $this->generateListParameters([
                'user' => $user->getTitle(),
                'userId' => $user->getId(),
            ])->toArray()
        );
    }

    /**
     * @Route("/{city}/{category}/{slug}/{id}", name="detail", requirements={"id" = "[\d]+"})
     *
     * @param int                $id
     * @param CategoryRepository $categoryRepository
     *
     * @return Response
     */
    public function show(int $id, CategoryRepository $categoryRepository): Response
    {
        $parameters = $this->generateShowParameters($id, $categoryRepository)->toArray();

        $response = $this->render('deals/show.html.twig', $parameters);
        $response->setSharedMaxAge(3600);
        $response->headers->addCacheControlDirective('must-revalidate', true);

        return $response;
    }
}

src/Controller/User/AnalyticsController.php
<?php

declare(strict_types=1);

namespace App\Controller\User;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/utilisateur", name="user_")
 */
class AnalyticsController extends AbstractController
{
    /**
     * @Route("/", name="dashboard")
     *
     * @return Response
     */
    public function index()
    {
        return $this->render('user/index.html.twig');
    }
}

src/Controller/User/OrdersController.php
<?php

declare(strict_types=1);

namespace App\Controller\User;

use App\Entity\PostDeal;
use App\Services\Crud;
use HakimCh\PaginateBundle\Services\Paginate;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/utilisateur/order", name="user_order_")
 */
class OrdersController extends AbstractController
{
    /**
     * @Route(
     *     "/{pageName}/{page}",
     *     defaults={"pageName" = "page", "page" = 1},
     *     requirements={"pageName" = "page", "page" = "[\d]+"},
     *     name="list"
     * )
     *
     * @param Paginate $paginate
     *
     * @return Response
     */
    public function list(Paginate $paginate): Response
    {
        return new Response();
    }

    /**
     * @Route("/add/{id}", name="add")
     *
     * @param PostDeal $deal
     * @param Crud $crud
     *
     * @return Response
     */
    public function add(PostDeal $deal, Crud $crud)
    {
        return new Response();
    }
}

src/Controller/User/ProfileController.php
<?php

declare(strict_types=1);

namespace App\Controller\User;

use App\Form\UserProfileType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/utilisateur", name="user_")
 */
class ProfileController extends AbstractController
{
    /**
     * @Route("/profil", name="profile")
     *
     * @param Request $request
     *
     * @return Response
     */
    public function profile(Request $request)
    {
        $user = $this->getUser();
        $form = $this->createForm(UserProfileType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // process data
        }

        return $this->render('user/profil.html.twig', [
            'form' => $form->createView(),
        ]);
    }
}

src/Controller/User/RegisterController.php
<?php

declare(strict_types=1);

namespace App\Controller\User;

use App\Entity\User;
use App\Form\UserRegisterType;
use App\Security\Encoder\LegacyEncoder;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class RegisterController extends AbstractController
{
    /**
     * @Route("/inscription/annonceur", name="register_user")
     *
     * @param Request       $request
     * @param LegacyEncoder $passwordEncoder
     *
     * @return Response
     */
    public function register(Request $request, LegacyEncoder $passwordEncoder): Response
    {
        $user = new User();
        $form = $this->createForm(UserRegisterType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user->setEncodedPassword($passwordEncoder);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('login_page');
        }

        return $this->render('user/inscription.html.twig', [
            'form' => $form->createView(),
        ]);
    }
}

templates/user/deal/index.html.twig
{% extends "user/layout.html.twig" %}

{% block memberContent %}

    <div class="alert alert-complete">
        <p>NB : toute modification de vos deals impliquera la validation de la part de notre équipe. (Dans les 24H qui suivent)</p>
    </div>

    <div class="user-actions align-right">
        <a href="{{ path('user_deal_add') }}" class="btn-complete">Ajouter</a>
    </div>

    {% if paginate.items and paginate.items|length > 0 %}
        {% for item in paginate.items %}
        <div class="item">
            <div class="item-infos">
                <div class="item-title">
                    {% if item.status == 'pending' %}
                        <span class="badge badge-warning">En validation</span>
                    {% else %}
                        <span class="badge badge-success">Publié</span>
                    {% endif %}
                    <strong>{{ item.title }}</strong>
                </div>
                <ul class="item-metas">
                    <li>Déposé le <strong>{{ item.createdAt|date('d/m/Y H:i') }}</strong></li>
                    <li>Dans <strong>{{ item.category.title }}</strong></li>
                </ul>
            </div>
            <div class="item-actions">
                <a href="{{ path('user_classified_update', { 'id': item.id }) }}" class="btn btn-complete">Modifier</a>
                {% if item.isArchived %}
                    <a href="{{ path('user_classified_archive', { 'archive': 'archiver', 'id': item.id }) }}" class="btn btn-success">Publier</a>
                {% else %}
                    <a href="{{ path('user_classified_archive', { 'archive': 'publier', 'id': item.id }) }}" class="btn btn-danger">Archiver</a>
                {% endif %}
                <a href="{{ path('user_classified_show', { 'id': item.id }) }}" class="btn btn-primary">Consulter</a>
            </div>
        </div>
        {% endfor %}
    {% else %}
        <div class="empty-bloc">
            Vous n'avez pas encore ajouter un deal
        </div>
    {% endif %}

{% endblock %}

templates/user/deal/order.html.twig
{% extends 'user/layout.html.twig' %}

{% block content %}

    <div id="orderPage">

        <div class="alert alert-info">
            <p>NB : veuillez lire les conditions ci-dessous</p>
        </div>

        <i class="ion-ios-checkmark-outline"></i>
        <div id="orderNumber">
            <strong>Numéro de commande</strong>
            <span>{{ orderNumber }}</span>
        </div>
        <p>Un mail vous a été envoyé avec toutes les informations nécessaires.</p>
    </div>

{% endblock %}

templates/user/deal/save.html.twig
{% extends "user/layout.html.twig" %}

{% form_theme form "form/theme.html.twig" %}

{% block memberContent %}
    <div class="alert alert-complete">
        <p>NB : toute modification de vos deals impliquera la validation de la part de notre équipe. (Dans les 24H qui suivent)</p>
    </div>

    {{ form_start(form) }}
        {{ form_row(form.title) }}
        <div class="row">
            <div class="col-sm-4 col-xs-12">
                {{ form_row(form.category) }}
            </div>
            <div class="col-sm-4 col-xs-12">
                {{ form_row(form.price) }}
            </div>
            <div class="col-sm-4 col-xs-12">
                {{ form_row(form.discount) }}
            </div>
        </div>
        <div class="row">
            <div class="col-sm-9 col-xs-12">
                {{ form_row(form.address) }}
            </div>
            <div class="col-sm-3 col-xs-12">
                {{ form_row(form.city) }}
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6 col-xs-12">
                {{ form_row(form.minimumRequirement) }}
            </div>
            <div class="col-sm-6 col-xs-12">
                {{ form_row(form.maximumRequirement) }}
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6 col-xs-12">
                {{ form_row(form.startAt) }}
            </div>
            <div class="col-sm-6 col-xs-12">
                {{ form_row(form.endAt) }}
            </div>
        </div>
        {% include 'blocs/live-uploader.html.twig' with {
            keys: ['photo1', 'photo2', 'photo3', 'photo4'],
            pictures: pictures
        } %}
        {{ form_row(form.content) }}
        <div class="form-action pull-right">
            <input type="submit" value="Enregistrer">
        </div>
    {{ form_end(form, {'render_rest': false}) }}
{% endblock %}