src/Entity/User.php
<?php

declare(strict_types=1);

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\Encoder\BasePasswordEncoder;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Users.
 *
 * @ORM\HasLifecycleCallbacks
 * @ORM\Table(name="user", uniqueConstraints={@ORM\UniqueConstraint(name="email", columns={"email"})})
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface, \Serializable
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(type="json_array", length=255)
     */
    private $roles = ['ROLE_USER'];

    /**
     * @ORM\Column(type="string", length=5, nullable=true, options={"default" = "M"}))
     */
    private $civility;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     * @Assert\NotBlank
     * @Assert\Email
     */
    private $email;

    /**
     * @ORM\Column(type="boolean", nullable=true, options={"default" = "0"})
     */
    private $newsletter;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex(
     *     "/(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}/",
     *     message="Le mot de passe n'est pas valide. Il doit avoir au minimum 8 caractères, une lettre et un nombre."
     * )
     */
    private $password;

    /**
     * @ORM\Column(name="is_active", type="boolean", nullable=true, options={"default" = "0"}))
     */
    private $isActive;

    /**
     * @ORM\Column(type="string", length=255, nullable=true))
     */
    private $headline;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Image
     */
    private $photo;

    /**
     * @ORM\Column(type="string", length=15, nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="boolean", nullable=true, options={"default" = true})
     */
    private $confirmation;

    /**
     * @ORM\Column(type="datetime", nullable=true, options={"default" = "1970-01-01"})
     */
    private $birthAt;

    /**
     * @ORM\Column(type="datetime", nullable=true, options={"default" = "1970-01-01"})
     */
    private $connectedAt;

    /**
     * @ORM\Column(type="datetime", nullable=true, options={"default" = "1970-01-01"})
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime", nullable=true, options={"default" = "1970-01-01"})
     */
    private $updatedAt;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\PostDealOrders", mappedBy="user")
     */
    private $dealOrders;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\PubCampaigns", mappedBy="user")
     */
    private $pubCampaigns;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Category", inversedBy="users", cascade={"persist", "merge"})
     * @ORM\JoinTable(name="user_categories")
     */
    private $categories;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\PostDeal", mappedBy="user")
     */
    private $deals;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\PostClassified", mappedBy="user")
     */
    private $classifieds;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\PostArticle", mappedBy="user")
     */
    private $articles;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\PostEvent", mappedBy="user")
     */
    private $events;

    /**
     * @var string
     */
    private $salt;

    public function __construct()
    {
        $this->isActive = true;
        $this->categories = new ArrayCollection();
        $this->classifieds = new ArrayCollection();
        $this->deals = new ArrayCollection();
        $this->dealOrders = new ArrayCollection();
        $this->pubCampaigns = new ArrayCollection();
        $this->events = new ArrayCollection();
        $this->articles = new ArrayCollection();
    }

    /**
     * @ORM\PreUpdate
     * @ORM\PrePersist
     *
     * @throws \Exception
     */
    public function onUpdate(): void
    {
        $this->updatedAt = new \DateTime();
        $this->username = Slugify::create()->slugify($this->firstName.' '.$this->lastName);
    }

    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id): void
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getConfirmation()
    {
        return $this->confirmation;
    }

    /**
     * @param mixed $confirmation
     */
    public function setConfirmation($confirmation): void
    {
        $this->confirmation = $confirmation;
    }

    /**
     * @return mixed
     */
    public function getNewsletter()
    {
        return $this->newsletter;
    }

    /**
     * @param mixed $newsletter
     */
    public function setNewsletter($newsletter): void
    {
        $this->newsletter = $newsletter;
    }

    public function getFirstName()
    {
        return $this->firstName;
    }

    public function setFirstName($firstName): void
    {
        $this->firstName = $firstName;
    }

    public function getLastName()
    {
        return $this->lastName;
    }

    /**
     * @param mixed $lastName
     */
    public function setLastName($lastName): void
    {
        $this->lastName = $lastName;
    }

    /**
     * @return string
     */
    public function getTitle(): ?string
    {
        return $this->firstName.' '.$this->lastName;
    }

    public function getUsername()
    {
        return $this->username;
    }

    public function setUsername($username): void
    {
        $this->username = $username;
    }

    public function getEmail()
    {
        return $this->email;
    }

    public function setEmail($email): void
    {
        $this->email = $email;
    }

    public function getPassword()
    {
        return $this->password;
    }

    public function setPassword($password): void
    {
        $this->password = $password;
    }

    public function getSaltedPassword($password)
    {
        return $password.$this->email;
    }

    public function setEncodedPassword(BasePasswordEncoder $encoder)
    {
        $this->password = $encoder->encodePassword(
            $this->getSaltedPassword($this->password),
            $this->getSalt()
        );
    }

    public function getSalt()
    {
        return 'aé&scr65+^p$msqµ£+*';
    }

    /**
     * @return mixed
     */
    public function getCivility()
    {
        return $this->civility;
    }

    /**
     * @param mixed $civility
     */
    public function setCivility($civility): void
    {
        $this->civility = $civility;
    }

    /**
     * @return mixed
     */
    public function getHeadline()
    {
        return $this->headline;
    }

    /**
     * @param mixed $headline
     */
    public function setHeadline($headline): void
    {
        $this->headline = $headline;
    }

    /**
     * @return mixed
     */
    public function getPhoto()
    {
        return $this->photo;
    }

    /**
     * @param mixed $photo
     */
    public function setPhoto($photo): void
    {
        $this->photo = $photo;
    }

    /**
     * @return mixed
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * @param mixed $phone
     */
    public function setPhone($phone): void
    {
        $this->phone = $phone;
    }

    public function isActive()
    {
        return $this->isActive;
    }

    public function setIsActive($isActive): void
    {
        $this->isActive = $isActive;
    }

    public function getBirthAt()
    {
        return $this->birthAt;
    }

    public function setBirthAt($birthAt): void
    {
        $this->birthAt = $birthAt;
    }

    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    public function setCreatedAt($createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt($updatedAt): void
    {
        $this->updatedAt = $updatedAt;
    }

    /**
     * @return mixed
     */
    public function getisActive()
    {
        return $this->isActive;
    }

    /**
     * @return mixed
     */
    public function getClassifieds()
    {
        return $this->classifieds;
    }

    /**
     * @return mixed
     */
    public function getDeals()
    {
        return $this->deals;
    }

    public function getRoles(): array
    {
        return $this->roles;
    }

    /**
     * @param array $roles
     */
    public function setRoles($roles): void
    {
        $this->roles = $roles;
    }

    public function eraseCredentials()
    {
    }

    /** @see \Serializable::serialize() */
    public function serialize()
    {
        return serialize([
            $this->id,
            $this->username,
            $this->password,
            $this->isActive,
            $this->salt,
        ]);
    }

    /**
     * @see \Serializable::unserialize()
     *
     * @param $serialized
     */
    public function unserialize($serialized)
    {
        [
            $this->id,
            $this->username,
            $this->password,
            $this->isActive,
            $this->salt
            ] = unserialize($serialized, ['allowed_classes' => false]);
    }

    /**
     * Checks whether the user's account has expired.
     *

src/Form/EventType.php
<?php

declare(strict_types=1);

namespace App\Form;

use App\Entity\PostEvent;
use DateTime;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\FormBuilderInterface;

class EventType extends PostType
{
    protected $dataClass = PostEvent::class;

    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        parent::buildForm($builder, $options);
        $now = (new DateTime())->format('Y-m-dTH:i');

        $builder
            ->add('startAt', DateTimeType::class, [
                'label' => 'start start',
                'widget' => 'single_text',
                'attr' => ['value' => $now],
            ])
            ->add('endAt', DateTimeType::class, [
                'label' => 'end date',
                'widget' => 'single_text',
                'attr' => ['value' => $now],
            ])
            ->remove('category');
    }
}

src/Controller/Api/EventController.php
<?php

declare(strict_types=1);

namespace App\Controller\Api;

use App\Repository\PostEventRepository;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\RouterInterface;

/**
 * @Route("/api/event", name="api_event_")
 */
class EventController
{
    /**
     * @Route("/", name="all")
     *
     * @param PostEventRepository $repository
     * @param RouterInterface     $router
     *
     * @return JsonResponse
     */
    public function all(PostEventRepository $repository, RouterInterface $router): JsonResponse
    {
        $items = [];
        $events = $repository->getRssFeed();

        foreach ($events as $event) {
            $startAt = $event->getStartAt();
            $endAt = $event->getEndAt();
            $items[] = [
                'id' => $event->getId(),
                'name' => $event->getTitle(),
                'startdate' => $startAt->format('Y-m-d'),
                'enddate' => $endAt->format('Y-m-d'),
                'starttime' => $startAt->format('H:i'),
                'endtime' => $endAt->format('H:i'),
                'color' => $this->getColor(),
                'url' => $router->generate('events_detail', [
                    'category' => $event->getCategory()->getSlug(),
                    'slug' => $event->getSlug(),
                    'id' => $event->getId(),
                ]),
            ];
        }

        return new JsonResponse(['monthly' => $items]);
    }

    private function getColor()
    {
        $colors = [
            '#F1654C', '#3E4651', '#2C82C9', '#8A2D3C', '#43353D', '#1D2247', '#D98B3A', '#42729B', '#45362E', '#63393E', '#3C3741',
            '#282830', '#953163', '#00587A', '#444B54', '#5C9F97', '#9E5428', '#1F9EA3', '#34495E', '#462446', '#A42A15', '#203040', '#3F3F3F', '#3F303F', '#E74C3C',
            '#5E412F', '#16A086', '#16A086', '#0F6177', '#025159', '#64C4AF', '#453E4A', '#3DA4AB', '#4387B5', '#BD3C4E', '#E74C3C', '#2C3E50', '#E74C3C', '#11132F',
        ];

        return $colors[rand(0, 38)];
    }
}

src/Controller/Post/EventsController.php
<?php

declare(strict_types=1);

namespace App\Controller\Post;

use App\Entity\PostEvent;
use App\Normalizers\EventNormalizer;
use App\Repository\CategoryRepository;
use HakimCh\SeoBundle\Exceptions\ParameterNormalizerNotFoundException;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/evenements", name="events_")
 */
class EventsController extends AbstractPostController
{
    /**
     * @var string
     */
    protected $entityClassName = PostEvent::class;
    /**
     * @var string
     */
    protected $normalizer = EventNormalizer::class;
    /**
     * @var int
     */
    protected $itemsPerPage = PostEvent::MAX_POST_PER_PAGE;

    /**
     * @Route("/{pageName}/{page}", defaults={"pageName" = "page", "page" = 1}, requirements={"pageName" = "page", "page" = "[\d]+"}, name="home")
     *
     * @throws ParameterNormalizerNotFoundException
     *
     * @return Response
     */
    public function list(): Response
    {
        return $this->render(
            'events/index.html.twig',
            $this->generateListParameters()->toArray()
        );
    }

    /**
     * @Route("/categorie/{category}/{pageName}/{page}", defaults={"pageName" = "page", "page" = 1}, name="category", requirements={"category" = "[\w-]+", "pageName" = "page", "page" = "[\d]+"})
     *
     * @param string $category
     *
     * @throws ParameterNormalizerNotFoundException
     *
     * @return Response
     */
    public function listByCategory(string $category): Response
    {
        return $this->render(
            'events/index.html.twig',
            $this->generateListParameters(['category' => $category])->toArray()
        );
    }

    /**
     * @Route("/{category}/{slug}/{id}", name="detail", requirements={"id" = "[\d]+"})
     *
     * @param int                $id
     * @param CategoryRepository $categoryRepository
     *
     * @return Response
     */
    public function show(int $id, CategoryRepository $categoryRepository): Response
    {
        $response = $this->render(
            'events/show.html.twig',
            $this->generateShowParameters($id, $categoryRepository)->toArray()
        );
        $response->setSharedMaxAge(3600);
        $response->headers->addCacheControlDirective('must-revalidate', true);

        return $response;
    }
}

templates/events/feed.xml.twig
<?xml version="1.0"?>
<monthly>
    {% for event in events %}
    <event>
        <id>{{ event.id }}</id>
        <name>{{ event.post_titre }}</name>
        <startdate>{{ event.start_at|date('Y-m-d') }}</startdate>
        <enddate>{{ event.endt_at|date('Y-m-d') }}</enddate>
        <starttime>{{ event.start_at|date('H:i') }}</starttime>
        <endtime>{{ event.endt_at|date('H:i') }}</endtime>
        <color>#ffb128</color>
        <url>{{ asset('evenements/' ~ event.slug ~ '/' ~ event.id) }}</url>
    </event>
    {% endfor %}
</monthly>

templates/events/index.html.twig
{% extends "base.html.twig" %}

{% block stylesheet %}
    <link rel="stylesheet" href="{{ asset('build/css/plugins/monthly.css') }}">
    <link rel="stylesheet" href="{{ asset('css/events.css') }}">
{% endblock %}

{% block pageTitle %}
    <h1>{{ seo.title }}</h1>
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="monthly" id="calendar"></div>
        <div class="row reset-margin">
            {% if paginate.items is defined and paginate.items|length > 0 %}
                {% for item in paginate.items %}
                    <div class="col-md-3 col-sm-6 article-item">
                        {% include 'blocs/event.html.twig' with {item: item} %}
                    </div>
                {% endfor %}
                {% include "@Paginate/pagination.html.twig" with {links: paginate.links} %}
            {% else %}
                <div class="empty-bloc">
                    Il n'y a aucun annonce listé pour cette recherche.
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block javascript %}
    {{ parent() }}
    <script type="text/javascript" src="{{ asset('build/js/plugins/monthly.js') }}"></script>
    <script>
        $(window).load( function() {
            $('#calendar').monthly({
                mode: 'event',
                dataType: 'json',
                jsonUrl: '{{ path('api_event_all') }}'
            });
        });
    </script>
{% endblock %}

templates/events/show.html.twig
{% extends "base.html.twig" %}

{% block stylesheet %}
    <link rel="stylesheet" href="{{ asset('build/css/v2/article.css') }}">
{% endblock %}

{% block seo_meta %}
    {% include 'blocs/og-metas.html.twig' with {
        url: path('events_detail', {slug: item.slug, id: item.id}),
        image: asset('/build/images/posts/' ~ item.photo)
    } %}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="page_header">
            <h1 class="title">{{ item.title }}</h1>
            <h3 class="meta">
                Commence le
                <time datetime="{{ item.startAt|date('U') }}">{{ item.startAt|date('d/m/Y H:i') }}</time> jusqu'au
                <time datetime="{{ item.endAt|date('U') }}">{{ item.endAt|date('d/m/Y H:i') }}</time> / vue par
                <span>{{ item.count }}</span> personnes
            </h3>
        </div>
        <div class="article">
            <div class="article_content">
                {% include "blocs/slide-show.html.twig" with {photos: item.photos, title: item.title, targetDir: 'posts'}%}

                <div class="article__story">
                    {{ item.content|raw }}
                </div>

                {#{{ shareToSocial(post_titre, post_content)|raw }}#}

                {% include 'shared/disqus.twig' with {'uid' : 'EVENT' ~ item.id, 'title' : item.title} %}

            </div>
            <div class="article_sidebar">
                {% if related is defined and related|length > 0 %}
                    <div class="articles">
                        <h2 class="bloc_title">Evenements à venir</h2>
                        {% for item in related %}
                            <a class="bloc_article" href="{{ path('events_detail', {category: item.category.slug, slug: item.slug, id: item.id}) }}">
                                <div class="bloc__image" style="background-image: url({{ resize(item.photo, 80, 80, 'events') }})"></div>
                                <h3 class="bloc__title">{{ item.title }}</h3>
                                <time datetime="{{ item.startAt|date('U') }}" class="bloc__date">{{ item.startAt|date('d/m/Y H:i') }}</time>
                            </a>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}